spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/netanalysis
    username: postgres
    password: bbb49da3ad6a40bab35f15ecf427a007
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
