spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/netanalysis
    username: netuser
    password: netpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
